[pl_pl] Added new translations
NeunEinser/bingo pull request #103
Opened 2022-01-04 02:21 UTC by Kri5t0fK

- item init error message
- More Settings sign
- Game Start messages
- team join messages
- category chests info
- lobby documentation
- sniper bingo
- consistency with official MC translations (unisex)

2022-01-04 19:08 UTC, NeunEinser commented
Pulled from master with some more translation changes.

2022-01-05 12:43 UTC, Kri5t0fK commented
Added translations for things from 2dc2c91

2022-02-06 12:26 UTC, NeunEinser requested changes

2022-02-06 12:26 UTC, NeunEinser commented on assets/bingo/lang/pl_pl.json
> +	"bingo.lobby.team_selection.join_magenta": "Gracz @s dołączył do karmazynowej drużyny.",
```suggestion
	"bingo.lobby.team_selection.join_red": "Gracz %s dołączył do czerwonej drużyny.",
	"bingo.lobby.team_selection.join_orange": "Gracz %s dołączył do pomarańczowej drużyny.",
	"bingo.lobby.team_selection.join_yellow": "Gracz %s dołączył do żółtej drużyny.",
	"bingo.lobby.team_selection.join_lime_green": "Gracz %s dołączył do jasnozielonej drużyny.",
	"bingo.lobby.team_selection.join_dark_green": "Gracz %s dołączył do ciemnozielonej drużyny.",
	"bingo.lobby.team_selection.join_cyan": "Gracz %s dołączył do błękitnej drużyny.",
	"bingo.lobby.team_selection.join_light_blue": "Gracz %s dołączył do jasnoniebieskiej drużyny.",
	"bingo.lobby.team_selection.join_dark_blue": "Gracz %s dołączył do niebieskiej drużyny.",
	"bingo.lobby.team_selection.join_purple": "Gracz %s dołączył do fioletowej drużyny.",
	"bingo.lobby.team_selection.join_magenta": "Gracz %s dołączył do karmazynowej drużyny.",
```

Placeholder is messed up on these

2022-02-06 15:54 UTC, NeunEinser approved these changes

2022-02-06 15:56 UTC, merged